const {
  REACT_APP_BASE_API_URL,
  REACT_APP_JWT_SECRET_KEY,
  REACT_APP_BASE_SOCKET_URL,
} = process.env;

export const BASE_API_URL = REACT_APP_BASE_API_URL;
export const BASE_SOCKET_URL = REACT_APP_BASE_SOCKET_URL;
export const JWT_SECRET_KEY = REACT_APP_JWT_SECRET_KEY;
